function NMD = m_coords2ald(NMD)
	 formats ='%1.5e'

      if strcmp(NMD.x0.type(2).str,'GAMMA')
	 for l=1:1:length(NMD.x0.pos(:,1))
		if NMD.x0.pos(l,2) == 1
			NMD.ald.coords1{l}=strcat(NMD.x0.atype(1).str,' \t',...
					num2str(NMD.x0.LJ.sigma.*NMD.x0.pos(l,3),formats),'\t',...
					num2str(NMD.x0.LJ.sigma.*NMD.x0.pos(l,4),formats),'\t',...
					num2str(NMD.x0.LJ.sigma.*NMD.x0.pos(l,5),formats))
		else		  
			NMD.ald.coords1{l}=strcat(NMD.x0.atype(2).str,' \t',...
					num2str(NMD.x0.LJ.sigma.*NMD.x0.pos(l,3),formats),'\t',...
					num2str(NMD.x0.LJ.sigma.*NMD.x0.pos(l,4),formats),'\t',...
					num2str(NMD.x0.LJ.sigma.*NMD.x0.pos(l,5),formats))
		end
	 end
       else
	 for l=1:1:length(NMD.x0.superlattice.direct(:,1))
		if NMD.x0.m(l) == 1
			NMD.ald.coords1{l}=strcat(NMD.x0.atype(1).str,' \t',...
					num2str(NMD.x0.LJ.sigma.*NMD.x0.ucell.cart(l,1),formats),'\t',...
					num2str(NMD.x0.LJ.sigma.*NMD.x0.ucell.cart(l,2),formats),'\t',...
					num2str(NMD.x0.LJ.sigma.*NMD.x0.ucell.cart(l,3),formats))
		else		  
			NMD.ald.coords1{l}=strcat(NMD.x0.atype(2).str,' \t',...
					num2str(NMD.x0.LJ.sigma.*NMD.x0.ucell.cart(l,1),formats),'\t',...
					num2str(NMD.x0.LJ.sigma.*NMD.x0.ucell.cart(l,2),formats),'\t',...
					num2str(NMD.x0.LJ.sigma.*NMD.x0.ucell.cart(l,3),formats))
		end
	 end
       end
	NMD.ald.coords = sprintf('%s \n',NMD.ald.coords1{:})
end
