lj.eps = 1.67E-21;              
lj.sigma = 3.4E-10;
lj.mass = 6.6326E-26;
lj.tau = sqrt((lj.mass*(lj.sigma)^2)/lj.eps);

kb = 1.3806E-23; 

str='Data_fullBZ.xls'
fid = fopen(str,'rt'); 
dummy = textscan(fid, '%f%f%f%f%f%f%f%f%f%f%f', 'HeaderLines',1); 
fclose(fid);

life=load('4p_life.dat');
freq=load('4p_freq.dat');
loglog(freq,life,'ro')
hold on
loglog(dummy{4}(:)*2.1427,dummy{8}(:)*1e-12,'o')

%legend('NMD','ALD')

set(gca, ...
  'Box'         , 'on'     , ...
  'TickDir'     , 'in'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         , ...
  'units',       'inches', ...
  'Position', [1 1 3.5 3.5]);

set(gcf, 'PaperPositionMode', 'auto');
print -depsc2 NMD_v_ALD.eps
